###
#  Bio
###
title: Rishikesh Darandale
email: Rishikesh.Darandale@gmail.com
gravatar: https://s.gravatar.com/avatar/5d0385085f0116785d4a9dde15acc67d?s=300
description: > # this means to ignore newlines until "baseurl:"
  Detail-oriented programmer and lead with 11+ years success
  devising innovative and tailored solutions to meet ever-changing
  business requirements within diverse industries. Advanced skill with leading-edge
  programming tools complemented by proven ability to assimilate and
  rapidly utilize emerging technologies.
github: rishikeshdarandale
linkedin:
twitter:
facebook:
instagram:
stackoverflow:
  

     

