# Refeence Config file
#  - https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
###
#  Bio
###
locale                   : "en"
title                    : "Rishikesh Darandale"
title_separator          : "-"
name                     : "Rishikesh Darandale"
description              : > # this means to ignore newlines until "baseurl:"
  Detail-oriented programmer and lead with 11+ years success
  devising innovative and tailored solutions to meet ever-changing
  business requirements within diverse industries. Advanced skill with leading-edge
  programming tools complemented by proven ability to assimilate and
  rapidly utilize emerging technologies.
url                      : https://rishikeshdarandale.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
atom_feed:
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification : xY9zvOqqxLsWYvLpoY1Q6UVD2MTGHVyKDPpnAHk7nWY
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles  


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - LICENSE
  - Rakefile
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: blogs/page:num
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Jekyll Plugins
gems:
  - jekyll-sitemap

  

     

