###
#  Bio
###
title: Rishikesh Darandale
description: > # this means to ignore newlines until "baseurl:"
  Detail-oriented programmer and lead with 11+ years success
  devising innovative and tailored solutions to meet ever-changing
  business requirements within diverse industries. Advanced skill with leading-edge
  programming tools complemented by proven ability to assimilate and
  rapidly utilize emerging technologies.

  

     

